# ─── Stage 1: Install ALL dependencies (dev + prod) for build ─────────────────
FROM node:22-alpine AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Enable pnpm via corepack
# Pin to pnpm@8 to match pnpm-lock.yaml lockfileVersion '6.0' (created with pnpm v8).
# Upgrading to pnpm@9/10 requires regenerating pnpm-lock.yaml locally first.
RUN corepack enable && corepack prepare pnpm@8 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile


# ─── Stage 2: Build the Next.js application ───────────────────────────────────
FROM node:22-alpine AS builder

RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@8 --activate

# ── Build-time public env vars ─────────────────────────────────────────────────
# NEXT_PUBLIC_* are inlined into the JS bundle during `next build`.
# Set these via build args or --build-arg on `docker build`.
ARG NEXT_PUBLIC_AUTH_MODE=real
ARG NEXT_PUBLIC_INVENTARIS_MODE=real
ENV NEXT_PUBLIC_AUTH_MODE=$NEXT_PUBLIC_AUTH_MODE
ENV NEXT_PUBLIC_INVENTARIS_MODE=$NEXT_PUBLIC_INVENTARIS_MODE

# ── Order status UUIDs ────────────────────────────────────────────────────────
# These UUIDs are seeded once into the database and are the same across all
# environments. Default values match the seed data in the repository.
# Override via build args if your database uses different seed UUIDs.
ARG NEXT_PUBLIC_JUST_IN_ORDER_STATUS_ID=e7f281a6-22cb-4f7c-ad6e-0588996515f4
ARG NEXT_PUBLIC_ON_PROCESS_ORDER_STATUS_ID=4df54409-695e-4fef-b519-46608ac9e0a5
ARG NEXT_PUBLIC_READY_ORDER_STATUS_ID=5b6b821f-6fc3-469c-9a2a-f0ffbef05a80
ARG NEXT_PUBLIC_COMPLETE_ORDER_STATUS_ID=044b4c5b-a8c0-45e8-b00d-8ecbaec2ba68
ARG NEXT_PUBLIC_CANCEL_ORDER_STATUS_ID=365894dd-f81b-435f-b19b-44cae066f351
ENV NEXT_PUBLIC_JUST_IN_ORDER_STATUS_ID=$NEXT_PUBLIC_JUST_IN_ORDER_STATUS_ID
ENV NEXT_PUBLIC_ON_PROCESS_ORDER_STATUS_ID=$NEXT_PUBLIC_ON_PROCESS_ORDER_STATUS_ID
ENV NEXT_PUBLIC_READY_ORDER_STATUS_ID=$NEXT_PUBLIC_READY_ORDER_STATUS_ID
ENV NEXT_PUBLIC_COMPLETE_ORDER_STATUS_ID=$NEXT_PUBLIC_COMPLETE_ORDER_STATUS_ID
ENV NEXT_PUBLIC_CANCEL_ORDER_STATUS_ID=$NEXT_PUBLIC_CANCEL_ORDER_STATUS_ID

# ── Feature flags ─────────────────────────────────────────────────────────────
# NEXT_PUBLIC_SIMULATE_PAYMENT_SUCCESS: enables a "Simulate Success" button for
# Midtrans payment testing. Must be false in production.
ARG NEXT_PUBLIC_SIMULATE_PAYMENT_SUCCESS=false
ENV NEXT_PUBLIC_SIMULATE_PAYMENT_SUCCESS=$NEXT_PUBLIC_SIMULATE_PAYMENT_SUCCESS

# Provide a placeholder so the API client module doesn't throw during build.
ENV API_BASE_URL=http://placeholder-buildtime
# Signal Next.js we're in the production build phase so conditional build-only
# code paths (like skipping API calls in client.ts) are triggered correctly.
ENV NEXT_PHASE=phase-production-build

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN pnpm build


# ─── Stage 3: Production runtime (minimal image) ──────────────────────────────
FROM node:22-alpine AS runner

# wget is used by HEALTHCHECK below
RUN apk add --no-cache wget

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
# Bind to all interfaces so Docker can reach the server from the host
ENV HOSTNAME="0.0.0.0"

# ── Security: run as non-root ──────────────────────────────────────────────────
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# ── Copy standalone output produced by `output: 'standalone'` in next.config ──
# .next/standalone contains a trimmed Node.js server (server.js) + only the
# required node_modules subset — no need to copy the full node_modules.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public           ./public

USER nextjs

EXPOSE 3000

# Health endpoint provided by app/api/health/route.ts
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1

# server.js is the entry point generated by Next.js standalone output
CMD ["node", "server.js"]
