# ─── Stage 1: Install ALL dependencies (dev + prod) for build ─────────────────
FROM node:22-alpine AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Enable pnpm via corepack
# Pin to pnpm@8 to match pnpm-lock.yaml lockfileVersion '6.0' (created with pnpm v8).
# Upgrading to pnpm@9/10 requires regenerating pnpm-lock.yaml locally first.
RUN corepack enable && corepack prepare pnpm@8 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile


# ─── Stage 2: Build the Next.js application ───────────────────────────────────
FROM node:22-alpine AS builder

RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@8 --activate

# ── Build-time public env vars ─────────────────────────────────────────────────
# NEXT_PUBLIC_* are inlined into the JS bundle during `next build`.
# Set these via build args or --build-arg on `docker build`.
ARG NEXT_PUBLIC_AUTH_MODE=real
ARG NEXT_PUBLIC_INVENTARIS_MODE=real
ENV NEXT_PUBLIC_AUTH_MODE=$NEXT_PUBLIC_AUTH_MODE
ENV NEXT_PUBLIC_INVENTARIS_MODE=$NEXT_PUBLIC_INVENTARIS_MODE

# Provide a placeholder so the API client module doesn't throw during build.
ENV API_BASE_URL=http://placeholder-buildtime
# Signal Next.js we're in the production build phase so conditional build-only
# code paths (like skipping API calls in client.ts) are triggered correctly.
ENV NEXT_PHASE=phase-production-build

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN pnpm build


# ─── Stage 3: Production runtime (minimal image) ──────────────────────────────
FROM node:22-alpine AS runner

# wget is used by HEALTHCHECK below
RUN apk add --no-cache wget

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
# Bind to all interfaces so Docker can reach the server from the host
ENV HOSTNAME="0.0.0.0"

# ── Security: run as non-root ──────────────────────────────────────────────────
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# ── Copy standalone output produced by `output: 'standalone'` in next.config ──
# .next/standalone contains a trimmed Node.js server (server.js) + only the
# required node_modules subset — no need to copy the full node_modules.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public           ./public

USER nextjs

EXPOSE 3000

# Health endpoint provided by app/api/health/route.ts
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1

# server.js is the entry point generated by Next.js standalone output
CMD ["node", "server.js"]
